### ISSUE TITLE
Stripe Customers show differently for Sportified vs STYFL

### ISSUE THREAD

**Issue by leaguetek01** [game7/sportified#117]
Not sure if we have an opportunity to fix, but each transaction creates a new Customer record in Strip for STYFL, but for us only a single record gets created.

**Comment by game7** [comment]
I mentioned this a few weeks back - the complexity to fix this is very high.  The stripe customer id for the platform is associated with the user in our system and is not tenant-scoped.  In order to ensure a single customer record in a connected account we would likely need to introduce tenant-scoped user and credit card info in our application - my thought was that this is a lot of work that could be put to better use in other areas.

There may be a possibility to locate an existing customer record in the connected account using some other identifier that we pass in, but I don't remember seeing any mention of this in the docs.  I'll take a look around.

**Comment by game7** [comment]
I've reviewed the stripe API docs and unfortunately the only way to retrieve an existing customer record is by ID, which means if we wish to maintain a single instance of each customer within a connected account we will need to maintain that tenant/customer relationship on our side AND also do the same for the customer/card (otherwise we'd probably see redundant credit cards within the customer).   

What do you think on this one?  I know that I'd like them to be unique on the stripe side but I really don't want to build something to manage this.  If we think this will be confusing or look like a poor design, perhaps we can also ask "why" we need the customer record and "what" one would do with that record on the stripe side - because it can also work just fine with no customer record and we can add customer-related metadata to the payment record.  Any effort saved by not building the synchronization design could be used to implement other features on our side to replace anything that may be lost by dropping the customer record from stripe.  Thoughts?

**Comment by game7** [comment]
actually, now that I look at the customer record more closely I don't think it really serves much purpose for us... at least not under our current design, given that we're not using stripe for subscriptions or invoices.  In fact, by setting up the customer record we enable the connected account to create subsequent payments outside of our application and thus free of our service fee.

![image](https://cloud.githubusercontent.com/assets/262805/21212721/89796ed8-c24c-11e6-9b03-1ae75e7b90c4.png)

I'm beginning to feel pretty strongly that we should drop the customer record and replace by enhanced metadata on the payment record.

**Comment by game7** [comment]
I believe this has been resolved by adding the stripe metadata in lieu of connected accounts
