### ISSUE TITLE
Calandar Export

### ISSUE THREAD

**Issue by OIATempe** [game7/sportified#211]
Can the excel export be formatted? 
   currently they are "general" and no matter what we try to change it do it does not change. 

Meaning.... 
The "date" be a date field (so we can change it and be able to sort by date)  
The "Start time" formatted to time (so that if we change the time on the sheet it will be in the correct format)

**Comment by game7** [comment]
a couple things we can do here...

1. if/when you open a csv but just clicking on it I'm pretty sure excel will always treat the columns as "general".  If you want the columns to be of type "date" and "time" I think you need to open the .csv using one of the options under the "Data" tab in excel, in which case excel will provide a transformation tool that will inspect the data and change the column types.  it's an extra step or two unfortunately
2. if you prefer to just open the csv by clicking, we can probably change the format of the date and time so that it sorts correctly as a "general" column... for example, we could add an extra column that does year-month-date hour:minute and this would allow them to be easily sorted chronologically

**Comment by game7** [comment]
fixed by 0191896184b10951278ad703ee06860e43eab881.  should be landing in a few minutes 😎

**Comment by game7** [comment]
ready -- give it try  👍

![image](https://user-images.githubusercontent.com/262805/92164781-c1eebc00-edea-11ea-9aa3-b37fdae89b47.png)

**Comment by OIATempe** [comment]
Perfect that works

Crystal Wade
Oceanside Ice Arena
480-941-0944 x 10
