### ISSUE TITLE
Modify Roster

### ISSUE THREAD

**Issue by OIATempe** [game7/sportified#73]
I have no way to add a player to the team. I can add his to the roster for that game but not to the team roster...

**Comment by game7** [comment]
The team administration pages are now accessible from the [league dashboard page](http://www.oceansideicearena.net/admin/league/seasons/17).  First go to `/admin`, then choose "programs"... select your desired program from the list to get to the program page, then choose the season from the right and you'll get the dashboard below.  _(Yes - we will be adding quick links to active league/seasons so that we can jump right from the main dashboard or from the public league pages)_

![image](https://cloud.githubusercontent.com/assets/262805/15437118/3470f238-1e7a-11e6-8d1f-81ef3e24941d.png)

Along the right you will find a list of teams grouped by division - just click a team and you'll get to the admin page.

![image](https://cloud.githubusercontent.com/assets/262805/15437149/5b13598a-1e7a-11e6-98de-75d7a63472ea.png)
