### ISSUE TITLE
Over 30 Issues

### ISSUE THREAD

**Issue by OIATempe** [game7/sportified#78]
- [x] I can not get to the statsheet for the 5/5 Games .... I get the error page
- [ ] All the CAHL game labels went back to CAHL (instead of the custom team name we had in there) 
- [x] If I go to edit the game it defaults to Spring 2012 and no team names.

**Comment by game7** [comment]
2 of 3 issues have been resolved.  Can you let me know where you are seen team names that are not overridden?  I can see that the custom names are used properly when building the game summary so there must be some other place that needs correction.

**Comment by OIATempe** [comment]
Pick any Over 30 game of CAHL vs... The custom name was the team name from
Ice den but has been reverted back to CAHL..


Crystal Koontz
OIA Admin. Manager
480-941-0944 x 10

**Comment by game7** [comment]
Unless I'm missing something... the vast majority of the O30 games are exactly as they were when loaded on 5/11.  The upload file that you provided had the CAHA team and we never performed custom name assignment on them.

![image](https://cloud.githubusercontent.com/assets/262805/15558019/c5e14a82-228b-11e6-80ba-f7e71899f049.png)

I'm looking into the database now and am confident that no games have reverted to CAHL and I know this because none of the games with "CAHL" currently showing have every been touched since loaded.

![image](https://cloud.githubusercontent.com/assets/262805/15558085/4258f06a-228c-11e6-9020-57111b645004.png)

Besides the timestamps there is further evidence because the custom team name flags are currently empty for all games with CAHL.  When a game is updated through the website these flags will always have either TRUE or FALSE as with the games that have been manually-entered or had scores posted... but when games are loaded through the backend these fields are empty until subsequently edited through the web front end.

![image](https://cloud.githubusercontent.com/assets/262805/15558150/cb9a132c-228c-11e6-806a-ca49801aa2d8.png)

**Comment by OIATempe** [comment]
I will manually in again and change them.

Yes they were uploaded CAHL but Adam and I went in to each of those games
and changed it to the CAHL team. No big deal now that the other issue is
fixed.


Crystal Koontz
OIA Admin. Manager
480-941-0944 x 10

**Comment by game7** [comment]
Closing this one per conversation with Crystal.
